version: '3.8'

services:
  # サービス名（dev-containerなど、ご自身の分かりやすい名前を付けます）
  dev-container:
    # DockerイメージID
    image: ttorch-nvidia:u22.04c12.2t2.2.0v1

    # コンテナ名
    container_name: diffusion-lm

    # ポートフォワーディング
    ports:
      - "15267:8888" # Jupyter Notebook (ホスト側:コンテナ側)
      - "25267:8097" # Visdom Dashboard

    # ボリュームマウント（フォルダの共有）
    volumes:
      # 作業ディレクトリ（./ は docker-compose.yml がある場所を指します）
      - ./:/work

    # GPUの使用設定
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              # "all" を指定するか、特定のGPU番号を列挙します (例: ["0", "1"])
              capabilities: [gpu]
              # all を指定する場合は count: all は不要なケースもあります。
              # 特定のGPUを指定する場合: device_ids: ['0']
              count: 3

    # スクリプトにあったその他のオプション
    shm_size: '2gb' # --shm-size=2048m と同等
    restart: always